version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /packages/conda-trampoline
    schedule:
      interval: weekly
    groups:
      rust:
        patterns:
          - "*"

  - package-ecosystem: conda
    directory: /
    schedule:
      interval: weekly
    groups:
      conda:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      python:
        patterns:
          - "*"
